# Licensed Materials - Property of IBM
# IBM Sterling Order Management (5725-D10), IBM Order Management (5737-D18)
# (C) Copyright IBM Corp. 2018, 2020 All Rights Reserved.
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
version: '3'
services:
  db2server:
    image: ${DB_IMAGE}:${DB_TAG}
    ports:
      - "${DB_PORT}:${DB_PORT_IMAGE}"
    entrypoint: /bin/bash
    command: ["/tmp/oms/init_db2_instance.sh"]
    environment:
      - DUMMY_PATH_PROP=1
      - LICENSE=${DTK_LICENSE}
      - DB2INST1_PASSWORD=${DB_PASS}
      - DB_DATA=${DB_DATA}
      - DB_BACKUP_RESTORE=${DB_BACKUP_RESTORE}
      - DB_BACKUP_FILE=${DB_BACKUP_FILE}
      - DB_IMPORTDATA=${DB_IMPORTDATA}
      - BLU=false
      - ENABLE_ORACLE_COMPATIBILITY=true
      - UPDATEAVAIL=NO
      - SAMPLEDB=false
      - REPODB=false
      - IS_OSXFS=false
      - PERSISTENT_HOME=true
      - HADR_ENABLED=false
    volumes:
      - ./db2server:/tmp/oms
      - ./db2server/create_database.sh:/var/custom/create_database.sh
      - database:/database
      - shared:/var/oms
    privileged: true
    container_name: om-db2server
  omruntime:
    image: ${OM_IMAGE}:${OM_TAG}
    command: ["sleep","infinity"]
    environment:
      - DUMMY_PATH_PROP=1
      - EAR=${RT}/external_deployments/smcfs.ear
    volumes:
      - ear:${RT}/external_deployments
      - ./omruntime:/tmp/oms
      - ${MQ_JNDI_DIR}:${MQ_JNDI_DIR2}
      - shared:/var/oms
    depends_on:
      - db2server
    container_name: om-runtime
  appserver:
    image: ${AP_IMAGE}:${AP_TAG}
    command: ["/opt/ibm/wlp/bin/server", "run", "defaultServer"]
    ports:
      - "${AP_HTTP_PORT}:9080"
      - "${AP_HTTPS_PORT}:9443"
      - "${AP_DEBUG_PORT}:8383"
    depends_on:
      - omruntime
    environment:
      - DUMMY_PATH_PROP=1
    volumes:
      - ear:/config/dropins
      - ./appserver:/tmp/oms
      - ./appserver/jvm.options:/config/jvm.options
      - ./appserver/server.xml:/config/server.xml
      - ${MQ_JNDI_DIR}:${MQ_JNDI_DIR2}
      - shared:/var/oms
    container_name: om-appserver
  mqserver:
    image: ${MQ_IMAGE}:${MQ_TAG}
    ports:
      - "${MQ_PORT}:1414"
      - "${MQ_HTTP_PORT}:9443"
    entrypoint: /bin/bash
    command: ["/tmp/oms/mq-init.sh"]
    environment:
      - DUMMY_PATH_PROP=1
      - LICENSE=${DTK_LICENSE}
      - MQ_QMGR_NAME=${MQ_QMGR_NAME}
      - MQ_JNDI_DIR=${MQ_JNDI_DIR2}
      - MQ_CONNECTION_FACTORY_NAME=${MQ_CONNECTION_FACTORY_NAME}
      - MQ_HOST=${MQ_HOST}
      - MQ_PORT=${MQ_PORT}
    volumes:
      - var_mqm:/mnt/mqm
      - shared:/var/oms
      - ./mqserver:/tmp/oms
      - ./mqserver/listener.mqsc:/etc/mqm/listener.mqsc
      - ${MQ_JNDI_DIR}:${MQ_JNDI_DIR2}
    container_name: om-mqserver
volumes:
  shared:
    driver: local
  var_mqm:
    driver: local
  ear:
    driver: local
  database:
    driver: local
